### ISSUE TITLE
python39.dll is missing

### ISSUE THREAD

**Issue by hhaeb** [4tegs/traccar2gpx#1]
correct me if i am wrong:
traccar2gpx.exe 
is a Windows app
it runs on win 10
it runs on python-3.11.0 

I see only a alert "traccar2gpx.exe - System error" [...] python39.dll not found[...]

<img width="311" alt="Screenshot 2022-12-02 221228" src="https://user-images.githubusercontent.com/2345812/205388588-91fcddf7-4fbc-4535-9e38-e1f7c43a8818.png">

**Comment by 4tegs** [comment]
This was a an error in my compile. Should work now.
