### ISSUE TITLE
add deviceId to file name

### ISSUE THREAD

**Issue by undee123** [4tegs/traccar2gpx#10]
Hallo Hans,

great work, your script was exactly we were looking for as we have a fleet of about 100 bikes with GPS tracker and want to analyze the data.
Only thing we are missing is the deviceId that is not included in the filename nor in the data itself, though it should be included in the exported data from traccar, shouldn't it?
As I'm not so familiar with Python a hint would be useful where to add it in the code so I'll try for myself.

Thank you very much!

Andreas

**Comment by 4tegs** [comment]
Hi Andreas,I‘m travelling these days. Get in contact with you as soon as I return.Mit freundlichen Grüßen,Hans Straßgütl Am 07.06.2024 um 11:02 schrieb undee123 ***@***.***>:﻿
Hallo Hans,
great work, your script was exactly we were looking for as we have a fleet of about 100 bikes with GPS tracker and want to analyze the data.
Only thing we are missing is the deviceId that is not included in the filename nor in the data itself, though it should be included in the exported data from traccar, shouldn't it?
As I'm not so familiar with Python a hint would be useful where to add it in the code so I'll try for myself.
Thank you very much!
Andreas

**Comment by 4tegs** [comment]
Hi Andreas,

back from my trip I had a look to your mail. From my view, the device ID 
is not missing, as I provide the trackers name which to me is more 
sounding.
Is there a difference between your name and device iD? Should we have a 
short conversation?
If yes, send me a personal message to ***@***.*** and I share my tel 
number.

Regards, Hams



------ Originalnachricht ------
Von "undee123" ***@***.***>
An "4tegs/traccar2gpx" ***@***.***>
Cc "Subscribed" ***@***.***>
Datum 07.06.2024 10:02:27
Betreff [4tegs/traccar2gpx] add deviceId to file name (Issue #10)

**Comment by 4tegs** [comment]
Unfortunately no response from Andreas. Closing issue.

**Comment by 4tegs** [comment]
Unfortunately no response from Andreas. Closing issue.
