### ISSUE TITLE
No way to run

### ISSUE THREAD

**Issue by guenter1952** [4tegs/traccar2gpx#2]
It seems, that there are different things to install.
The program asks for python39.dll. After downloading and registering the DLL the program ask nothing anymore and does nothing anymore.

**Comment by 4tegs** [comment]
Are you sure you have downloaded the latest version (1.2b) and reworked the traccar2gpx.json? The issue you describe has happened in an older version and I expected it to be fixed.
No way for me to recreate the issue...

**Comment by 4tegs** [comment]
One thought: What happens if you start the exe without the traccar2gpx.json being around?

**Comment by guenter1952** [comment]
I used an old version. The newer one works great.... if the .json-file ist edited accordingly.
