### ISSUE TITLE
Export all data

### ISSUE THREAD

**Issue by smilebasti** [4tegs/traccar2gpx#3]
Hi,
i found your project because Home assistant stopped supporting Traccar. Now i am stuck with traccar v5.2.

Is it somehow possible to export the whole database to weekly gpx files? In the Readme file there is a 90 days limit. Would it be possible to select days 1-7 as one file, 8-14 as another file and so on?

Thanks

**Comment by 4tegs** [comment]
In the meanwhile, in fact there is a limit at 399 days.
Your request to export ranges of dates is what is covered by Traccar itself using the replay function.

**Comment by smilebasti** [comment]
Thanks for the reply.
What replay function do you mean?

With my version i am not able to call the api /postion with application/gpx+xml as header. This means my Traccar version doesn't have the possibility to export gpx format with the api.

**Comment by 4tegs** [comment]
As far as I recall, the application/gpx+xml api  call has been established with Traccar v5.4. 
The readme in section Compatibility states that the program was tested with 5.4 (meanwhile with 5.5 too).

Traccar export either through
      Traccar - Reports - Export
or on the map, click the respective tracker, the tracker popup window opens, you select the 270° circle (second from left) and the replay window opens.
