### ISSUE TITLE
Fatal error: "No connection adapters were found for..."

### ISSUE THREAD

**Issue by digdilem** [4tegs/traccar2gpx#7]
Tried this tool today, looks ideal for what I wanted, but no go I'm afraid.

Client is Windows 11, patched current. 

Server is debian, latest stable, and Traccar is at the latest version running in Docker.

The URL mentioned here is correct and working, and can be viewed via web browser from the same PC

The credentials supplied in the .json are correct and tested.

This error shows on start, after a few seconds deliberation. Cannot progress past this.

![image](https://github.com/4tegs/traccar2gpx/assets/4052275/6f6fd903-f683-4998-ae92-0eabe2d1aa9c)

**Comment by 4tegs** [comment]
I'm travelling these days, so not very responsive.

- Are you sure you the user you use has devices linked (as the error messaages look like that)
- What is your latest version running in docker? 5.10? With 5.10 there have been many changes and I haven't tested traccar2gpx with it yet.

**Comment by digdilem** [comment]
Thanks for your reply - and that's pretty responsive!

I only have one user account which I used to set it up. That account created the three devices and can see and interact with them normally. 

I followed [these instructions](https://github.com/traccar/traccar-docker), which look to be using traccar 5.12

Thanks again, and happy travels.

**Comment by 4tegs** [comment]
I upgraded my installation to 5.12 and everything works fine.
Your "root_url" is 10.1.0.1 with port 11001. You need to set http in front.....

"root_url": "http://10.1.0.1:11001" 

Let me know if it works.

**Comment by digdilem** [comment]
Well, that's embarassing!

Yes, that was the problem - and on re-reading the docs I can see that does reference using the protocol. I blame having to do similar things at work and most recently such fields explicitly required just the hostname. 

Anyway - thanks for your time - sorted!
