### ISSUE TITLE
Crash during start

### ISSUE THREAD

**Issue by pki791** [4tegs/traccar2gpx#8]
Hi.

I have used this a time ago, but now, when starting and connecting it throws:
Traceback (most recent call last):
  File "traccar2gpx.py", line 967, in <module>
  File "traccar2gpx.py", line 369, in get_all_devices
  File "traccar2gpx.py", line 326, in load_json
  File "json\__init__.py", line 293, in load
  File "encodings\cp1250.py", line 23, in decode
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 114032: character maps to <undefined>

![image](https://github.com/4tegs/traccar2gpx/assets/59803213/04a2bec8-954a-4194-871b-30d5c203b2af)

I am not sure if it has to do with devices names with special chars or something?

Can You please take a look or help me to diagnose deeper?

**Comment by 4tegs** [comment]
Hi Nameless,

I expect you to have a problem within your JSON file.
Is it still coded in UTF-8?
Are all commas set right?

If you want, you can send me your JSON and I'll have a look to it.

Regards
Hans

------ Originalnachricht ------
Von "pki791" ***@***.***>
An "4tegs/traccar2gpx" ***@***.***>
Cc "Subscribed" ***@***.***>
Datum 07.05.2024 18:09:08
Betreff [4tegs/traccar2gpx] Crash during start (Issue #8)

**Comment by pki791** [comment]
I think it is okay:
![image](https://github.com/4tegs/traccar2gpx/assets/59803213/063b83aa-0604-4e05-8a44-378a46af8811)

Also a traccar-result.json is created which confirms the login data is correct.

**Comment by 4tegs** [comment]
simplify: setup a test user, send me the credentials and I test it from 
here.
No other idea by now.


------ Originalnachricht ------
Von "pki791" ***@***.***>
An "4tegs/traccar2gpx" ***@***.***>
Cc "4tegs" ***@***.***>; "Comment" 
***@***.***>
Datum 07.05.2024 18:40:33
Betreff Re: [4tegs/traccar2gpx] Crash during start (Issue #8)

**Comment by pki791** [comment]
Created pull request with a fix. In some free time You can push the verion by Your convention and compile the executable.
